; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32
board = esp32s3box
framework = arduino

; This tells PIO to include the examples folder during compilation
build_src_filter = 
  +<*> 
  +<../.pio/libdeps/esp32s3box/lvgl/examples>

build_flags = 
    -D LV_CONF_INCLUDE_SIMPLE
    -I src/
    -D LV_USE_EXAMPLES=1
lib_deps = 
	lvgl/lvgl@^9.2.2
	tamctec/TAMC_GT911@^1.0.2
	moononournation/GFX Library for Arduino@1.5.0
	adafruit/Adafruit NeoPixel @ ^1.12.0
    adafruit/DHT sensor library @ ^1.4.6
    adafruit/Adafruit Unified Sensor @ ^1.1.14
